modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/minetraps/issues"

[[mods]]
modId="minetraps"
version="2.2.5-pre1"
displayName="MineTraps"
itemIcon="minetraps:pitfall_trap"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/MineTraps.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minetraps"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
This mod adds several new traps and blocks like mines, bear traps, nail traps, toxic mines, spikes and more!
'''

[[dependencies.minetraps]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minetraps]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
